### ISSUE TITLE
Enable/Disabling dlog at runtime

### ISSUE THREAD

**Issue by jedi4ever** [gauravk92/DLog#1]
I wonder if it is possible to enable logging at runtime: 
By default customers would have it disabled but when we detect issues we could remotely enable more verbose logging.

**Comment by gvkhna** [comment]
Sorry for the late reply. I think this is out of scope of this project for quick debugging. A lot of this code would never pass App Store review due to some private api's being used. I suggest using a more robust logging system for production. This is used mostly to get quick log statements thrown in the code for faster debugging. 

After this much time I'm curious what has happened since you posted, and what your thoughts are?

**Comment by jedi4ever** [comment]
We decided to go with CocoaLumberjack for logging + using a log services like @logentries
